on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get changed Python files
        run: |
          CHANGED_FILES=$(git diff --name-only $(git merge-base origin/main HEAD) | grep '^tests/.*\.py$')
          echo "Changed Python Test Files: $CHANGED_FILES"
          echo "::set-env name=CHANGED_FILES::$CHANGED_FILES"

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Package dependencies
        run: pip install -r requirements.txt

      - name: Run affected tests
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            python -m pytest -k "$(echo "$CHANGED_FILES" | tr '\n' ' ')"
          else
            echo "No Python test files changed. Skipping tests."
          fi
