on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get changed Python files
        run: | 
          BASE_BRANCH=$(git rev-parse origin/$(git rev-parse --abbrev-ref HEAD))
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep '^tests/.*\.py$' || true)
          echo "Changed Python Test Files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "base branch: $BASE_BRANCH"

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Package dependencies
        run: pip install -r requirements.txt

      - name: Run affected tests
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            python -m pytest -k "$(echo "$CHANGED_FILES" | tr '\n' ' ')"
          else
            echo "No Python test files changed. Skipping tests."
          fi
