name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'tests/**/*.py'

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'tests**/*.py')
          echo "Changed Python Files: $CHANGED_FILES"
          echo "::set-env name=CHANGED_FILES::$CHANGED_FILES"

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Package dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest ${{ env.CHANGED_FILES }}
